wandb_version: 1

activation_actor:
  value: relu
activation_critic:
  value: elu
batch_size:
  value: 123
buffer_size:
  value: 303399
gamma:
  value: 0.974226624503498
hidden_size:
  value: 49
lr:
  value: 0.0009505109745812806
noise_sd:
  value: 0.3284986657490516
num_layers:
  value: 2
