wandb_version: 1

activation_actor:
  value: tanh
activation_critic:
  value: elu
batch_size:
  value: 121
buffer_size:
  value: 118782
gamma:
  value: 0.9850699487473608
hidden_size:
  value: 30
lr:
  value: 0.0013745253159369692
noise_sd:
  value: 0.3263464427277032
num_layers:
  value: 4
