wandb_version: 1

activation_actor:
  value: tanh
activation_critic:
  value: elu
batch_size:
  value: 229
buffer_size:
  value: 248059
gamma:
  value: 0.97404027021518
hidden_size:
  value: 45
lr:
  value: 0.0016526942407729763
noise_sd:
  value: 0.3144980857310027
num_layers:
  value: 2
