program: tuner.py
command:
  - /usr/bin/env
  - python3.8
  - ${program}
  - ${args}
project: sweeps-td3
early_terminate:
  min_iter: 12
  type: hyperband
method: bayes
metric:
  goal: maximize
  name: rl_reward
parameters:
  batch_size:
    distribution: int_uniform
    max: 256
    min: 64
  buffer_size:
    distribution: int_uniform
    max: 350000
    min: 100000
  gamma:
    distribution: uniform
    max: 0.991
    min: 0.97
  hidden_size:
    distribution: int_uniform
    max: 96
    min: 16
  lr:
    distribution: uniform
    max: 0.002
    min: 0.0004
  noise_sd:
    distribution: uniform
    max: 0.4
    min: 0.15
  num_layers:
    distribution: int_uniform
    max: 4
    min: 1
