wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1655211876
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.8.10
      5: 0.12.16
      8:
      - 5
action_dim:
  desc: null
  value: 2
alpha:
  desc: null
  value: 0.7
batch_size:
  desc: null
  value: 128
beta_zero:
  desc: null
  value: 0.5
buffer_size:
  desc: null
  value: 200000
crossover_prob:
  desc: null
  value: 0.0
device:
  desc: null
  value: cuda
distil:
  desc: null
  value: true
distil_type:
  desc: null
  value: distance
elite_fraction:
  desc: null
  value: 0.2
env_name:
  desc: null
  value: LunarLanderContinuous-v2
frac_frames_train:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.98
individual_bs:
  desc: null
  value: 10000
learn_start:
  desc: null
  value: 3127.0
ls:
  desc: null
  value: 300
mutation_batch_size:
  desc: null
  value: 256
mutation_mag:
  desc: null
  value: 0.05
mutation_noise:
  desc: null
  value: false
mutation_prob:
  desc: null
  value: 0.9
next_save:
  desc: null
  value: 500
noise_clip:
  desc: null
  value: 0.5
noise_sd:
  desc: null
  value: 0.1
ns:
  desc: null
  value: false
ns_epochs:
  desc: null
  value: 10
num_evals:
  desc: null
  value: 3
num_frames:
  desc: null
  value: 1000000
opstat:
  desc: null
  value: false
opstat_freq:
  desc: null
  value: 1
per:
  desc: null
  value: false
policy_update_freq:
  desc: null
  value: 2
pop_size:
  desc: null
  value: 30
proximal_mut:
  desc: null
  value: true
render:
  desc: null
  value: false
replace_old:
  desc: null
  value: true
rl_to_ea_synch_period:
  desc: null
  value: 3
save_foldername:
  desc: null
  value: pderl/logs
save_periodic:
  desc: null
  value: false
seed:
  desc: null
  value: 7
state_dim:
  desc: null
  value: 8
tau:
  desc: null
  value: 0.005
test_operators:
  desc: null
  value: false
use_ddpg:
  desc: null
  value: false
use_done_mask:
  desc: null
  value: true
use_ounoise:
  desc: null
  value: false
verbose_crossover:
  desc: null
  value: false
verbose_mut:
  desc: null
  value: false
