wandb_version: 1

activation_actor:
  value: tanh
batch_size:
  value: 86
buffer_size:
  value: 150000
gamma:
  value: 0.97
hidden_size:
  value: 50
lr:
  value: 0.0008467946606025008
noise_sd:
  value: 0.24138966195598008
num_layers:
  value: 3
