wandb_version: 1

activation_actor:
  value: relu
batch_size:
  value: 64
buffer_size:
  value: 200000
gamma:
  value: 0.99
hidden_size:
  value: 50
lr:
  value: 0.0010481962946186593
noise_sd:
  value: 0.3227942375752624
num_layers:
  value: 2
