wandb_version: 1

activation_actor:
  value: relu
batch_size:
  value: 100
buffer_size:
  value: 150000
gamma:
  value: 0.97
hidden_size:
  value: 96
lr:
  value: 0.0018446155606757697
noise_sd:
  value: 0.22618069919708397
num_layers:
  value: 3
