wandb_version: 1

activation_actor:
  value: tanh
batch_size:
  value: 100
buffer_size:
  value: 150000
gamma:
  value: 0.99
hidden_size:
  value: 96
lr:
  value: 0.001937311276763634
noise_sd:
  value: 0.3297895152009991
num_layers:
  value: 2
