wandb_version: 1

activation_actor:
  value: relu
batch_size:
  value: 128
buffer_size:
  value: 100000
gamma:
  value: 0.99
hidden_size:
  value: 72
lr:
  value: 0.0009812374931274135
noise_sd:
  value: 0.3134871278778562
num_layers:
  value: 3
