wandb_version: 1

activation_actor:
  value: relu
batch_size:
  value: 64
buffer_size:
  value: 250000
gamma:
  value: 0.97
hidden_size:
  value: 96
lr:
  value: 0.000498761827574066
noise_sd:
  value: 0.29159580189620443
num_layers:
  value: 2
