wandb_version: 1

activation_actor:
  value: relu
batch_size:
  value: 86
buffer_size:
  value: 100000
gamma:
  value: 0.98
hidden_size:
  value: 50
lr:
  value: 0.0017586047463443227
noise_sd:
  value: 0.24871648928082443
num_layers:
  value: 3
